import os

lr_list = [5e-6, 1e-5, 2e-5, 5e-5, 1e-4]

for lr in lr_list:
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 n --lambda1 0.7 --lambda2 0.3 --test_file charlie > charlie1_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --wd 0.1 --lambda1 0.7 --lambda2 0.3 --test_file charlie > charlie1a_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --lambda1 0.7 --lambda2 0.3 --test_file charlie > charlie1b_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --wd 0.001 --lambda1 0.7 --lambda2 0.3 --test_file charlie > charlie1c_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 n --lambda1 0.8 --lambda2 0.2 --test_file charlie > charlie2_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --wd 0.1 --lambda1 0.8 --lambda2 0.2 --test_file charlie > charlie2a_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --lambda1 0.8 --lambda2 0.2 --test_file charlie > charlie2b_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --wd 0.001 --lambda1 0.8 --lambda2 0.2 --test_file charlie > charlie2c_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 n --lambda1 0.7 --lambda2 0.3 --test_file ottawa > ottawa1_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --wd 0.1 --lambda1 0.7 --lambda2 0.3 --test_file ottawa > ottawa1a_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --lambda1 0.7 --lambda2 0.3 --test_file ottawa > ottawa1b_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --wd 0.001 --lambda1 0.7 --lambda2 0.3 --test_file ottawa > ottawa1c_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 n --lambda1 0.8 --lambda2 0.2 --test_file ottawa > ottawa2_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --wd 0.1 --lambda1 0.8 --lambda2 0.2 --test_file ottawa > ottawa2a_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --lambda1 0.8 --lambda2 0.2 --test_file ottawa > ottawa2b_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --l2 y --wd 0.001 --lambda1 0.8 --lambda2 0.2 --test_file ottawa > ottawa2c_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 n --lambda1 0.7 --lambda2 0.3 --test_file charlie > charlie1_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --wd 0.1 --lambda1 0.7 --lambda2 0.3 --test_file charlie > charlie1a_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --lambda1 0.7 --lambda2 0.3 --test_file charlie > charlie1b_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --wd 0.001 --lambda1 0.7 --lambda2 0.3 --test_file charlie > charlie1c_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 n --lambda1 0.8 --lambda2 0.2 --test_file charlie > charlie2_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --wd 0.1 --lambda1 0.8 --lambda2 0.2 --test_file charlie > charlie2a_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --lambda1 0.8 --lambda2 0.2 --test_file charlie > charlie2b_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --wd 0.001 --lambda1 0.8 --lambda2 0.2 --test_file charlie > charlie2c_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 n --lambda1 0.7 --lambda2 0.3 --test_file ottawa > ottawa1_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --wd 0.1 --lambda1 0.7 --lambda2 0.3 --test_file ottawa > ottawa1a_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --lambda1 0.7 --lambda2 0.3 --test_file ottawa > ottawa1b_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --wd 0.001 --lambda1 0.7 --lambda2 0.3 --test_file ottawa > ottawa1c_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 n --lambda1 0.8 --lambda2 0.2 --test_file ottawa > ottawa2_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --wd 0.1 --lambda1 0.8 --lambda2 0.2 --test_file ottawa > ottawa2a_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --lambda1 0.8 --lambda2 0.2 --test_file ottawa > ottawa2b_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --veri_loss_fn w --l2 y --wd 0.001 --lambda1 0.8 --lambda2 0.2 --test_file ottawa > ottawa2c_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 n --lambda1 0.7 --lambda2 0.3 --test_file german > german1_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --wd 0.1 --lambda1 0.7 --lambda2 0.3 --test_file german > german1a_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --lambda1 0.7 --lambda2 0.3 --test_file german > german1b_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --wd 0.001 --lambda1 0.7 --lambda2 0.3 --test_file german > german1c_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 n --lambda1 0.8 --lambda2 0.2 --test_file german > german2_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --wd 0.1 --lambda1 0.8 --lambda2 0.2 --test_file german > german2a_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --lambda1 0.8 --lambda2 0.2 --test_file german > german2b_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --wd 0.001 --lambda1 0.8 --lambda2 0.2 --test_file german > german2c_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 n --lambda1 0.7 --lambda2 0.3 --test_file sydney > sydney1_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --wd 0.1 --lambda1 0.7 --lambda2 0.3 --test_file sydney > sydney1a_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --lambda1 0.7 --lambda2 0.3 --test_file sydney > sydney1b_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --wd 0.001 --lambda1 0.7 --lambda2 0.3 --test_file sydney > sydney1c_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 n --lambda1 0.8 --lambda2 0.2 --test_file sydney > sydney2_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --wd 0.1 --lambda1 0.8 --lambda2 0.2 --test_file sydney > sydney2a_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --lambda1 0.8 --lambda2 0.2 --test_file sydney > sydney2b_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --l2 y --wd 0.001 --lambda1 0.8 --lambda2 0.2 --test_file sydney > sydney2c_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 n --lambda1 0.7 --lambda2 0.3 --test_file german > german1_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --wd 0.1 --lambda1 0.7 --lambda2 0.3 --test_file german > german1a_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --lambda1 0.7 --lambda2 0.3 --test_file german > german1b_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --wd 0.001 --lambda1 0.7 --lambda2 0.3 --test_file german > german1c_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 n --lambda1 0.8 --lambda2 0.2 --test_file german > german2_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --wd 0.1 --lambda1 0.8 --lambda2 0.2 --test_file german > german2a_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --lambda1 0.8 --lambda2 0.2 --test_file german > german2b_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --wd 0.001 --lambda1 0.8 --lambda2 0.2 --test_file german > german2c_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 n --lambda1 0.7 --lambda2 0.3 --test_file sydney > sydney1_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --wd 0.1 --lambda1 0.7 --lambda2 0.3 --test_file sydney > sydney1a_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --lambda1 0.7 --lambda2 0.3 --test_file sydney > sydney1b_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --wd 0.001 --lambda1 0.7 --lambda2 0.3 --test_file sydney > sydney1c_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 n --lambda1 0.8 --lambda2 0.2 --test_file sydney > sydney2_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --wd 0.1 --lambda1 0.8 --lambda2 0.2 --test_file sydney > sydney2a_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --lambda1 0.8 --lambda2 0.2 --test_file sydney > sydney2b_w_{lr}.txt')
	os.system(f'python mtl_final.py --lr {lr} --model_name BERTWEET --gpu_id 1 --veri_loss_fn w --l2 y --wd 0.001 --lambda1 0.8 --lambda2 0.2 --test_file sydney > sydney2c_w_{lr}.txt')